/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admindashboard;

import Config.Session;
import Login.login;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Big Boss
 */
public class Admin extends javax.swing.JFrame {

    public Admin() {
        initComponents();

    }
    Color navcolor = new Color(255,204,204);
    Color hovercolor = new Color(226,0,56);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        acc_lname = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tenant = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        payments = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        userAcc = new javax.swing.JPanel();
        house = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("PINK.png"));
        Image img=icon.getImage();
        desktopPaneControl = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(img,0,0,getWidth(),getHeight(),this);

            }

        };

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(226, 0, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("ADMIN");
        jPanel1.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, -1));

        acc_lname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname.setText("ADMIN");
        jPanel1.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, 30));

        jPanel11.setBackground(new java.awt.Color(153, 0, 51));
        jPanel11.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vacancy Vista Management System");
        jPanel11.add(jLabel1);
        jLabel1.setBounds(250, 10, 690, 40);

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 70));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-admin-100.png"))); // NOI18N
        jPanel8.add(jLabel12);
        jLabel12.setBounds(20, 0, 110, 110);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 110));

        dash.setBackground(new java.awt.Color(226, 0, 56));
        dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashMouseExited(evt);
            }
        });
        dash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        dash.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 60));

        jPanel1.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 60));

        tenant.setBackground(new java.awt.Color(226, 0, 56));
        tenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tenantMouseExited(evt);
            }
        });
        tenant.setLayout(null);

        jLabel21.setBackground(new java.awt.Color(255, 0, 102));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tenants Registration");
        tenant.add(jLabel21);
        jLabel21.setBounds(20, 0, 233, 60);

        jPanel1.add(tenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 60));

        payments.setBackground(new java.awt.Color(226, 0, 56));
        payments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentsMouseExited(evt);
            }
        });
        payments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 0, 102));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Payments");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        payments.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 120, 50));

        jPanel1.add(payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, 50));

        userAcc.setBackground(new java.awt.Color(255, 0, 102));
        userAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userAccMouseExited(evt);
            }
        });
        userAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(userAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 260, -1));

        house.setBackground(new java.awt.Color(226, 0, 56));
        house.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                houseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                houseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                houseMouseExited(evt);
            }
        });
        house.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setText("Houses Overview");
        house.add(jLabel2);
        jLabel2.setBounds(50, 0, 200, 60);

        jPanel1.add(house, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 260, 60));

        desktopPaneControl.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopPaneControlLayout = new javax.swing.GroupLayout(desktopPaneControl);
        desktopPaneControl.setLayout(desktopPaneControlLayout);
        desktopPaneControlLayout.setHorizontalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneControlLayout.setVerticalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPaneControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 880, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();

        if (sess.getId() == 0) {
            JOptionPane.showMessageDialog(null, "No Account Found, Login First!");
            login lg = new login();
            lg.setVisible(true);
            this.dispose();
        } else {
            acc_name.setText("" + sess.getFn());
            acc_lname.setText("" + sess.getLn());
        }

    }//GEN-LAST:event_formWindowActivated

    private void dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseClicked
          
    }//GEN-LAST:event_dashMouseClicked

    private void dashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseEntered
        dash.setBackground(navcolor);
    }//GEN-LAST:event_dashMouseEntered

    private void dashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseExited
        dash.setBackground(hovercolor);
    }//GEN-LAST:event_dashMouseExited

    private void tenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenantMouseClicked
        desktopPaneControl.removeAll();
      RegTenants as =new RegTenants();
      desktopPaneControl.add(as).setVisible(true); 
    }//GEN-LAST:event_tenantMouseClicked

    private void tenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenantMouseEntered
        tenant.setBackground(navcolor);
    }//GEN-LAST:event_tenantMouseEntered

    private void tenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenantMouseExited
        tenant.setBackground(hovercolor);
    }//GEN-LAST:event_tenantMouseExited

    private void paymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseClicked
    desktopPaneControl.removeAll();
    Payment as =new Payment();
    desktopPaneControl.add(as).setVisible(true); 
    }//GEN-LAST:event_paymentsMouseClicked
 
    private void paymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseEntered
        payments.setBackground(navcolor);
    }//GEN-LAST:event_paymentsMouseEntered

    private void paymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseExited
        payments.setBackground(hovercolor);
    }//GEN-LAST:event_paymentsMouseExited

    private void userAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userAccMouseClicked

    private void userAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccMouseEntered
        userAcc.setBackground(navcolor);
    }//GEN-LAST:event_userAccMouseEntered

    private void userAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccMouseExited
        userAcc.setBackground(hovercolor);
    }//GEN-LAST:event_userAccMouseExited

    private void houseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseClicked
      desktopPaneControl.removeAll();
      rechouses as =new rechouses();
      desktopPaneControl.add(as).setVisible(true); 
    }//GEN-LAST:event_houseMouseClicked

    private void houseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseEntered
        house.setBackground(navcolor);
    }//GEN-LAST:event_houseMouseEntered

    private void houseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseExited
        house.setBackground(hovercolor);
    }//GEN-LAST:event_houseMouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
 
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         desktopPaneControl.removeAll();
        DashAdmin as =new DashAdmin();
        desktopPaneControl.add(as).setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel acc_name;
    private javax.swing.JPanel dash;
    public javax.swing.JDesktopPane desktopPaneControl;
    private javax.swing.JPanel house;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel payments;
    private javax.swing.JPanel tenant;
    private javax.swing.JPanel userAcc;
    // End of variables declaration//GEN-END:variables
}
