/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admindashboard;

import Config.DBConnector;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author scc-college
 */
public class rechouses extends javax.swing.JInternalFrame {

    private Connection connect;
    Connection cn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public rechouses() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        displayData();
    }
     public void displayData() {
        try {
            DBConnector DBConnector = new DBConnector();
            ResultSet rs = DBConnector.getData("SELECT * FROM houses");
            h_table.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Errors: " + ex.getMessage());
            
        }
        
    }
    
    Color navcolor = new Color(255, 204, 255);
    Color hovercolor = new Color(255, 0, 102);


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        d = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        p_add = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        p_edit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hn = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        s = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        stats = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        h_table = new javax.swing.JTable();
        p_add2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        d.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d);
        d.setBounds(10, 350, 130, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Due Date");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 300, 100, 34);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Price");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 590, 190, 34);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jTextField5);
        jTextField5.setBounds(10, 430, 390, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Occupant ID");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(20, 90, 121, 34);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jTextField6);
        jTextField6.setBounds(10, 130, 390, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Contact Number");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(20, 390, 170, 34);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(10, 530, 390, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("First Name");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(20, 190, 121, 34);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jTextField7);
        jTextField7.setBounds(10, 230, 390, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Last Name");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(20, 290, 121, 34);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jTextField8);
        jTextField8.setBounds(10, 330, 390, 50);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Number of Members");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(20, 490, 190, 34);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        p.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel3.add(p);
        p.setBounds(150, 350, 140, 40);

        p_add.setBackground(new java.awt.Color(255, 204, 255));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADD");
        p_add.add(jLabel6);
        jLabel6.setBounds(30, 0, 60, 40);

        jPanel3.add(p_add);
        p_add.setBounds(140, 540, 130, 40);

        p_edit.setBackground(new java.awt.Color(255, 204, 255));
        p_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_editMouseExited(evt);
            }
        });
        p_edit.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EDIT");
        p_edit.add(jLabel7);
        jLabel7.setBounds(20, 0, 79, 40);

        jPanel3.add(p_edit);
        p_edit.setBounds(160, 590, 110, 40);

        delete.setBackground(new java.awt.Color(255, 204, 255));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DELETE");
        delete.add(jLabel2);
        jLabel2.setBounds(20, 0, 90, 40);

        jPanel3.add(delete);
        delete.setBounds(20, 590, 130, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Status");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 500, 90, 34);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Price");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(150, 310, 70, 34);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("House Number");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(150, 50, 150, 34);

        hn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(hn);
        hn.setBounds(150, 90, 140, 40);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Water");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(150, 140, 90, 40);

        w.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        w.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(w);
        w.setBounds(150, 180, 140, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Maintenance");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(150, 220, 130, 34);

        m.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(m);
        m.setBounds(150, 260, 140, 40);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Security");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 220, 90, 34);

        s.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(s);
        s.setBounds(10, 260, 130, 40);

        e.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        e.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(e);
        e.setBounds(10, 180, 130, 40);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Electricity");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 140, 100, 40);

        stats.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "OCCUPIED" }));
        jPanel3.add(stats);
        stats.setBounds(20, 540, 110, 40);

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total);
        total.setBounds(20, 440, 260, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Total");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(30, 400, 220, 34);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("ID Number");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(10, 50, 110, 34);

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(id);
        id.setBounds(10, 90, 130, 40);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 300, 660));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOUSES RECORDS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 370, 50));

        h_table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        h_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        h_table.setGridColor(new java.awt.Color(204, 0, 102));
        h_table.setRowHeight(25);
        h_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(h_table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 560, 310));

        p_add2.setBackground(new java.awt.Color(255, 204, 255));
        p_add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add2MouseExited(evt);
            }
        });
        p_add2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRINT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        p_add2.add(jLabel8);
        jLabel8.setBounds(0, 0, 150, 50);

        jPanel2.add(p_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 150, 50));

        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setText("SEARCH");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchMouseReleased(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        if (hn.getText().isEmpty() || p.getText().isEmpty() || d.getText().isEmpty()) {

        } else {
            Connection cn = null;
            PreparedStatement save = null;

            try {
                DBConnector dc = new DBConnector();
                cn = dc.getConnection();

                String status = (String) stats.getSelectedItem();

                double electricity = Double.parseDouble(e.getText());
                double water = Double.parseDouble(w.getText());
                double maintenance = Double.parseDouble(m.getText());
                double security = Double.parseDouble(s.getText());
                double price = Double.parseDouble(p.getText());

                double totalValue = electricity + water + maintenance + security + price;

                save = cn.prepareStatement("INSERT INTO houses (h_number, h_status, h_price, h_date, h_electricity, h_water, h_maintencance, h_security, h_total) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ? , ?, ?)");
                save.setString(1, hn.getText());
                save.setString(2, status);
                save.setDouble(3, price);
                save.setString(4, d.getText());
                save.setDouble(5, electricity);
                save.setDouble(6, water);
                save.setDouble(7, maintenance);
                save.setDouble(8, security);
                save.setDouble(9, totalValue);

                int row = save.executeUpdate();

                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Record Added!");
                    displayData();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add record!");
                }
            } catch (SQLException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            } finally {
                try {
                    if (save != null) {
                        save.close();
                    }
                    if (cn != null) {
                        cn.close();
                    }
                } catch (SQLException ex) {
                    System.out.println("error" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_p_addMouseClicked

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
        p_add.setBackground(hovercolor);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
        p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void p_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseClicked
        int rowIndex = h_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        } else {
            Connection connection = null;
            PreparedStatement preparedStatement = null;

            try {

                String status = (String) stats.getSelectedItem();
                DBConnector dbConnector = new DBConnector();
                connection = dbConnector.getConnection();

                TableModel tbl = h_table.getModel();
                String selectedId = tbl.getValueAt(rowIndex, 0).toString();

                String updateQuery = "UPDATE houses SET h_number = ?, h_status = ?, h_price = ?,h_date = ?, h_electricity = ?, h_water = ?, h_maintencance = ?, h_security = ? , h_total = ? WHERE h_id = ?";
                preparedStatement = connection.prepareStatement(updateQuery);

                preparedStatement.setString(1, hn.getText());
                preparedStatement.setString(2, status);
                preparedStatement.setString(3, p.getText());
                preparedStatement.setString(4, d.getText());
                preparedStatement.setString(5, e.getText());
                preparedStatement.setString(6, w.getText());
                preparedStatement.setString(7, m.getText());
                preparedStatement.setString(8, s.getText());
                preparedStatement.setString(9, total.getText());
                preparedStatement.setString(10, selectedId);

                int rowsAffected = preparedStatement.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Record updated successfully!");
                    displayData();
                } else {
                    JOptionPane.showMessageDialog(null, "No data found for the selected item.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error updating data: " + ex.getMessage());
            } finally {
                try {
                    if (preparedStatement != null) {
                        preparedStatement.close();
                    }
                    if (connection != null) {
                        connection.close();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error updating data: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_p_editMouseClicked

    private void p_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseEntered
        p_edit.setBackground(hovercolor);
    }//GEN-LAST:event_p_editMouseEntered

    private void p_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseExited
        p_edit.setBackground(navcolor);
    }//GEN-LAST:event_p_editMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int rowIndex = h_table.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                DBConnector DBConnector = new DBConnector();
                TableModel tbl = h_table.getModel();
                String t_id = tbl.getValueAt(rowIndex, 0).toString();
                String sql = "DELETE FROM houses WHERE h_id = '" + t_id + "'";
                int affectedRows = DBConnector.updateData(sql);
                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(null, "Record deleted successfully!");
                    displayData();
                } else {
                    JOptionPane.showMessageDialog(null, "Record deletion failed!");
                }
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(hovercolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseExited

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void h_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h_tableMouseClicked
        int rowIndex = h_table.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        } else {
            TableModel model = h_table.getModel();

            String xid = model.getValueAt(rowIndex, 0).toString();
            String hnoValue = model.getValueAt(rowIndex, 1).toString();
            String hstatusValue = model.getValueAt(rowIndex, 2).toString();
            String hpriceValue = model.getValueAt(rowIndex, 3).toString();
            String hdateValue = model.getValueAt(rowIndex, 4).toString();
            String electricity = model.getValueAt(rowIndex, 5).toString();
            String water = model.getValueAt(rowIndex, 6).toString();
            String maintenance = model.getValueAt(rowIndex, 7).toString();
            String security = model.getValueAt(rowIndex, 8).toString();
            String totalValue = model.getValueAt(rowIndex, 9).toString();

            id.setText(xid);
            hn.setText(hnoValue);
            stats.setSelectedItem(hstatusValue);
            p.setText(hpriceValue);
            d.setText(hdateValue);
            e.setText(electricity);
            w.setText(water);
            m.setText(maintenance);
            s.setText(security);
            total.setText(totalValue);
        }
    }//GEN-LAST:event_h_tableMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        MessageFormat header = new MessageFormat("Transaction Reports");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            h_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException er) {
            System.out.println("" + er.getMessage());
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void p_add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseClicked

    }//GEN-LAST:event_p_add2MouseClicked

    private void p_add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseEntered
        p_add.setBackground(hovercolor);
    }//GEN-LAST:event_p_add2MouseEntered

    private void p_add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseExited
        p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_add2MouseExited

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseReleased

    }//GEN-LAST:event_searchMouseReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        DefaultTableModel tbl = (DefaultTableModel) h_table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(tbl);
        h_table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search.getText()));
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JPanel delete;
    private javax.swing.JTextField e;
    private javax.swing.JTable h_table;
    private javax.swing.JTextField hn;
    public static final javax.swing.JTextField id = new javax.swing.JTextField();
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField m;
    private javax.swing.JTextField p;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel p_add2;
    private javax.swing.JPanel p_edit;
    private javax.swing.JTextField s;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> stats;
    private javax.swing.JTextField total;
    private javax.swing.JTextField w;
    // End of variables declaration//GEN-END:variables
}
